apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: preciousproject3
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  JWT_SECRET: hello
  POSTGRESS_DB: postgres
  POSTGRESS_HOST: postgres.czsbrsaglqsf.us-east-1.rds.amazonaws.com
  URL: http://localhost:8100  
metadata:
  name: env-config
  